type: "orchestration"
version: "1.0"
pipeline:
  metadata:
    description: "Scheduling wrapper for Data Quality Monitor pipeline. Schedule this\
      \ pipeline to trigger quality checks."
    origin: "maia-37752454-bfb9-4018-a158-74729f2229da"
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Data Quality Monitor"
      parameters:
        componentName: "Start"
    Run Data Quality Monitor:
      type: "run-orchestration"
      parameters:
        componentName: "Run Data Quality Monitor"
        orchestrationJob: "data_quality_monitor"
        setScalarVariables:
        setGridVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId:
    Run Data Quality Monitor:
      position:
        x: 160
        "y": 0
      tempMetlId:
